### ISSUE TITLE
Error when policy is compliant?

### ISSUE THREAD

**Issue by gerhard-tinned** [claudijd/ssh_scan#32]
When the ssh_scan is executed against a server not matching the policy, the output works as described. But when it runs against a server that matches the policy, i get the following error message: 

$ ./bin/ssh_scan --target host.example.com --port 22 --policy policies/mozilla_intermediate.yml
/path/to/ssh_scan/lib/ssh_scan/policy_manager.rb:99:in `compliant?': undefined method `missing_policy_compression?' for #<SSHScan::PolicyManager:0x007f8c2a8c77e8> (NoMethodError)
Did you mean?  missing_policy_compression
	from /path/to/ssh_scan/lib/ssh_scan/policy_manager.rb:122:in `compliance_results'
	from /path/to/ssh_scan/lib/ssh_scan/scan_engine.rb:16:in `scan'
	from ./bin/ssh_scan:68:in `<main>'

Additional info: 
* OS is MacOSX

**Comment by claudijd** [comment]
@gerhard-tinned thanks for the bug report, I think it's fixed in #34 now

**Comment by claudijd** [comment]
@gerhard-tinned you can now update to a fixed version like so:

    $ gem update ssh_scan
    Updating installed gems
    Updating ssh_scan
    Successfully installed ssh_scan-0.0.6
    Parsing documentation for ssh_scan-0.0.6
    Installing ri documentation for ssh_scan-0.0.6
    Installing darkfish documentation for ssh_scan-0.0.6
    Done installing documentation for ssh_scan after 0 seconds
    Parsing documentation for ssh_scan-0.0.6
    Done installing documentation for ssh_scan after 0 seconds
    Gems updated: ssh_scan

Please let me know if you run into any more snags and I'd be happy to fix them for you.

**Comment by gerhard-tinned** [comment]
Thanks it works nicly now (used the git version so update was git pull origin master). 

Thanks. Now i  only have an issue when i install it on my server itself. Will create a seperate issue for that.
